db: archer
server:
  port: 8888
  servlet:
    context-path: /dev-api
    session:
      cookie:
        name: BIUSID
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,siro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.152.45:3306/${db}?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root1234
logging:
  path: ./logs
  level:
    com.mr.archer: debug

superAdmin:
  username: admin
  password: 111111
  nick: 系统管理员
  mail: jiang.feng@mr.com
  phone: 18888888888
  avatar: https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif
  roleName: 超级管理员
  roleDesc: 内置角色
  roleValue: SuperAdmin
  permValue: \*
  permName: 所有权限
